spring:
  datasource:
    url: jdbc:mysql://localhost:3308/ece
    username: root
    password: hasagihasagi456
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update

  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
